-- CreateEnum
CREATE TYPE "Segment" AS ENUM ('FIRMA_AKUNTAN', 'KONSULTAN_PAJAK', 'KONSULTAN_MANAJEMEN', 'MAHASISWA_MAGANG', 'KARYAWAN_AKUNTANSI');

-- AlterTable
ALTER TABLE "Firm" ADD COLUMN     "segment" "Segment" NOT NULL DEFAULT 'FIRMA_AKUNTAN';
