const { chromium } = require("playwright");
const EXE = "/Users/staff/Library/Caches/ms-playwright/chromium-1234/chrome-mac-arm64/Google Chrome for Testing.app/Contents/MacOS/Google Chrome for Testing";
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: EXE });
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
  await page.goto("https://web-production-7a593.up.railway.app/login", { waitUntil: "networkidle", timeout: 30000 });
  await page.fill('input[name="email"]', "admin@ledgerline.dev");
  await page.fill('input[name="password"]', "password123");
  await page.click('button[type="submit"]');
  await page.waitForURL("**/dashboard", { timeout: 25000 });
  await page.waitForTimeout(2500);
  console.log("URL:", page.url());
  console.log("TITLE:", await page.title());
  const nav = await page.$$eval("nav a, aside a, [role=navigation] a", els => els.map(e => ({ href: e.getAttribute("href"), text: (e.innerText || "").trim() })).filter(x => x.text));
  console.log("=== NAV LINKS ===");
  nav.forEach(n => console.log(" ", n.text, "->", n.href));
  const headings = await page.$$eval("h1,h2,h3", els => els.map(e => (e.innerText || "").trim()).filter(Boolean).slice(0, 40));
  console.log("=== HEADINGS ===");
  headings.forEach(h => console.log(" -", h.slice(0, 70)));
  await page.screenshot({ path: ".openclaw/tmp/live-dashboard.png" });
  console.log("SCREENSHOT: .openclaw/tmp/live-dashboard.png");
  await browser.close();
})().catch(e => { console.error("FAIL:", e.message); process.exit(1); });
